# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.9.16                   # https://pyreadiness.org/3.9
  - pip=22.1.2                      # https://pip.pypa.io/en/stable/news
  - pip:
      - rpaframework==23.5.1        # https://rpaframework.org/releasenotes.html
      - robocorp==0.2.0             # https://pypi.org/project/robocorp
      - robocorp-browser==1.0.2     # https://pypi.org/project/robocorp-browser
      - robocorp-excel==0.4.0       # https://pypi.org/project/robocorp-excel
      - robocorp-http==0.2.0        # https://pypi.org/project/robocorp-http
