# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.10.15                # https://pyreadiness.org/3.10
  - robocorp-truststore=0.8.0     # https://pypi.org/project/robocorp-truststore/
  - pip=24.2                      # https://pip.pypa.io/en/stable/news
  - pip:
    - rpaframework==28.6.3        # https://rpaframework.org/releasenotes.html
    - robocorp==2.1.2             # https://pypi.org/project/robocorp
    - robocorp-browser==2.3.4     # https://pypi.org/project/robocorp-browser
    - requests==2.32.3            # https://pypi.org/project/requests

